version: "3.3"
services:
  adminlte:
    build: .
    command: npm run dev
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
    - .:/code
    - /code/node_modules
  webserver:
    build:
      context: ./docker-services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - adminlte
